version: "3.7"

services:
  converter-api:
    build:
      context: .
      target: development
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    command: npm run start:dev 
    env_file:
      - .env
    networks:
      - converter-network
    depends_on:
      - converter-postgres
  converter-postgres:
    restart: always
    image: postgres:12
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    networks:
      - converter-network
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: converter
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - converter-pgdata:/var/lib/postgresql/data
networks:
  converter-network:
volumes:
  converter-pgdata:
